### ISSUE TITLE
Create connection oauth2 github and facebook

### ISSUE THREAD

**Issue by ZeroDiverse** [ZeroDiverse/Newcastle-organizer-server#18]

**Comment by StellaJung-Student** [comment]
@ZeroDiverse I would like to take this issue if it is not urgent. Since I need to study typescript :)

**Comment by ZeroDiverse** [comment]
Oh if you want to take it, you can take it then, i will let this open and create other issues for the one i assigned, good luck

**Comment by StellaJung-Student** [comment]
@ZeroDiverse Thanks~ hm I never used RDS, should I sign up for this?

**Comment by ZeroDiverse** [comment]
> @ZeroDiverse Thanks~ hm I never used RDS, should I sign up for this?

No for RDS you can use your localhost database username and passport itas on postgres @StellaJung-Student

**Comment by ZeroDiverse** [comment]
> > @ZeroDiverse Thanks~ hm I never used RDS, should I sign up for this?
> 
> No for RDS you can use your localhost database username and passport itas on postgres @StellaJung-Student 

Actually its localhost you just need google api oauth2 key to start the server

**Comment by StellaJung-Student** [comment]
@ZeroDiverse Great! Thanks and I have this error. do you know why?
![image](https://user-images.githubusercontent.com/59578350/100888168-cf682080-3483-11eb-8ae8-1736ea9e01a2.png)

**Comment by ZeroDiverse** [comment]
@StellaJung-Student Do you have the same username password for user stella in postgres? Its saying that your username password is false, the localhost postgresql, you can check that again, thanks

**Comment by StellaJung-Student** [comment]
Where can I set the auth info for postgres? should I run the docker compose? then what is the command?

**Comment by prashantrayamajhi** [comment]
> Where can I set the auth info for postgres? should I run the docker compose? then what is the command?

i believe you have postgres installed (if not, download postgres, dont worry it's very simple). Open psql shell , the default username is postgres and the default password is root, set that in the .env file too, then you are a good to go

**Comment by ZeroDiverse** [comment]
> Where can I set the auth info for postgres? should I run the docker compose? then what is the command?

@StellaJung-Student i dont really understand the first part but normally you can try psql or pgadmin for postgres for the server you can use .env file and copy all of those from .env.example and replace, if you need any more help pls tell me, i will send you the folder structure

**Comment by ZeroDiverse** [comment]
![image](https://user-images.githubusercontent.com/64563965/100893952-36093080-34bc-11eb-8dab-765a42d56c7b.png)

**Comment by ZeroDiverse** [comment]
For docker it's not fully setup yet since i just change the ormconfig.json to use in server config ( as you will see in server.ts )

@StellaJung-Student

**Comment by StellaJung-Student** [comment]
Oh~ you mean I need to install psql? and set the info in .env?
like AWS_RDS_HOST will be the postgresql server? and 'username and password' will be my local postgres user?
And INIT_DB will be postgres dbname?
Sorry for a lot of questions~.

**Comment by prashantrayamajhi** [comment]
> Oh~ you mean I need to install psql? and set the info in .env?
> like AWS_RDS_HOST will be the postgresql server? and 'username and password' will be my local postgres user?
> And INIT_DB will be postgres dbname?
> Sorry for a lot of questions~.

no problem at all! install psql and i will send you the .env file xD, gonna have to send it privately though

**Comment by StellaJung-Student** [comment]
@prashantrayamajhi Thanks a lot~, my email is sojung@myseneca.ca

**Comment by prashantrayamajhi** [comment]
> sojung@myseneca.ca

okay 👍

**Comment by prashantrayamajhi** [comment]
@StellaJung-Student  dont hesitate if you are stuck somewhere :)

**Comment by StellaJung-Student** [comment]
Finally I got it
![image](https://user-images.githubusercontent.com/59578350/100907506-66d76e80-3498-11eb-8ed0-99babfc2f3ed.png)
Thanks~ @prashantrayamajhi,  @ZeroDiverse

**Comment by prashantrayamajhi** [comment]
> Finally I got it
> ![image](https://user-images.githubusercontent.com/59578350/100907506-66d76e80-3498-11eb-8ed0-99babfc2f3ed.png)
> Thanks~ @prashantrayamajhi, @ZeroDiverse

nice :) no problem

**Comment by ZeroDiverse** [comment]
Np, if you have any more problems, happy to help @StellaJung-Student

**Comment by ZeroDiverse** [comment]
@StellaJung-Student I have update the code, please rebase to your branch

**Comment by StellaJung-Student** [comment]
I just made a PR, but I realized do you have client? using 3000 port?
I may need for a test.
And for github, I have a type issue so temporarily I skipped the line.
Please teach me more :) Thanks~

**Comment by ZeroDiverse** [comment]
@StellaJung-Student 

https://github.com/ZeroDiverse/Newcastle-organizer-client 

this one ^^

**Comment by StellaJung-Student** [comment]
Thanks, I will double-check it.

**Comment by ZeroDiverse** [comment]
@StellaJung-Student Great, if you need any help, you can tag or ping me or @prashantrayamajhi

**Comment by StellaJung-Student** [comment]
@prashantrayamajhi I tested it on my local and it worked well but on the PR, there is a test issue.
![image](https://user-images.githubusercontent.com/59578350/101247549-30902e00-36e8-11eb-869a-e9ec375b77c1.png)
This is my local's result but if you see my PR, I cannot pass the test. Please help me :)

**Comment by ZeroDiverse** [comment]
@StellaJung-Student You can't pass the test cause of the github ci /cd is not with database yet so don't worry, i will review your pr tonight

**Comment by prashantrayamajhi** [comment]
@StellaJung-Student  great job stella, your pr has been merged, we will configure some stuff in the frontend at then it's good to go!

**Comment by StellaJung-Student** [comment]
@prashantrayamajhi , @ZeroDiverse Thank you for helping me to experience.

**Comment by ZeroDiverse** [comment]
@StellaJung-Student no problem,we are gonna open more issues so if you want to do some you can comment to let us know

**Comment by ZeroDiverse** [comment]
And thanks for the great contribution
