### ISSUE TITLE
Setup passport js for authentication

### ISSUE THREAD

**Issue by prashantrayamajhi** [ZeroDiverse/Newcastle-organizer-server#7]

**Comment by ryboh1** [comment]
More details?

**Comment by prashantrayamajhi** [comment]
> More details?

create an api endpoint for auth via json web token

**Comment by StellaJung-Student** [comment]
@prashantrayamajhi , local passport would be OK?

**Comment by prashantrayamajhi** [comment]
> @prashantrayamajhi , local passport would be OK?

sure!

**Comment by StellaJung-Student** [comment]
@prashantrayamajhi I created [PR](https://github.com/ZeroDiverse/Newcastle-organizer-server/pull/10) for the issue, but realized the language was changed.
I don't know how to use typescript now~ let me know the next step~

**Comment by prashantrayamajhi** [comment]
> @prashantrayamajhi I created [PR](https://github.com/ZeroDiverse/Newcastle-organizer-server/pull/10) for the issue, but realized the language was changed.
> I don't know how to use typescript now~ let me know the next step~

well, there will be more issues to work on, also there is a client repository for the the frontend (react). are you on the discord server ? If not, i suggest you join in, you'll be updated about the project :)

**Comment by ZeroDiverse** [comment]
Yeah sorry for the changes, but after we have decide to move on to typescript for better use of typeorm, so sorry for that, if anyone still interested in it, you guys can rebase from lastest version in main

**Comment by ZeroDiverse** [comment]
> @prashantrayamajhi I created [PR](https://github.com/ZeroDiverse/Newcastle-organizer-server/pull/10) for the issue, but realized the language was changed.
> I don't know how to use typescript now~ let me know the next step~

if you like to have more information, you can join us here https://discord.gg/ukWb8SEe

**Comment by prashantrayamajhi** [comment]
> @prashantrayamajhi I created [PR](https://github.com/ZeroDiverse/Newcastle-organizer-server/pull/10) for the issue, but realized the language was changed.
> I don't know how to use typescript now~ let me know the next step~

**Comment by prashantrayamajhi** [comment]
@StellaJung-Student  thanks for your contribution. We will be using you code in typescript :)

**Comment by StellaJung-Student** [comment]
@ Np:) I will look at how you guys updates my code and I will learn from it.
I heard typeorm is great~ 
Thank you for the opportunity~
